# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f6153d60416ffdbb4d1f447de01aa4b733368c708506fff66ba71a300453175ab821c9ec17a8664e52792424cbdf19d069b41f43bb53679fe5648c0d9f4ee60

test:
  secret_key_base: 60a528611610aabf6735fca9c54e0a487fa70eb793441261edad8edf7c0cd05066031949b2f149b67cce1641f1649d5d03450ef4e01572313c96fdc98eb3e937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
